// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVnFxg8VAbfOCInET24fLhuGCIQTFFyY',
    appId: '1:104319031456:web:8c6bbe57c0a2a544f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    authDomain: 'niftyniota.firebaseapp.com',
    storageBucket: 'niftyniota.appspot.com',
    measurementId: 'G-4PZ08PW80T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiueUM63heaWyatCNprbv5urPizszpNaE',
    appId: '1:104319031456:android:97fe02f42c68ec0ff851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    storageBucket: 'niftyniota.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhfFT9C-U8LNr0d9h_gG1YI2L9xcqWuw',
    appId: '1:104319031456:ios:6276be7d93fa5f9cf851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    storageBucket: 'niftyniota.appspot.com',
    iosBundleId: 'com.example.niftyNiota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVnFxg8VAbfOCInET24fLhuGCIQTFFyY',
    appId: '1:104319031456:web:27681f43bdadd507f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    authDomain: 'niftyniota.firebaseapp.com',
    storageBucket: 'niftyniota.appspot.com',
    measurementId: 'G-3NEGFGM39H',
  );
}
